napi-rs/napi-rs

src/lib.rs

Hi, started using napi-rs instead of neon. Works very well so far.
I needed a few more functions to work with js objects and arrays and added them here. Originally based on the fork from @cztomsik  but rebased onto this master here.

Add more object functions.

---

napi/src/lib.rs
napi/src/sys/stable.rs

env.throw_error
String => JsString
JsString.as_str
Status into napi_status

feat(napi): tweaks

---

napi/src/lib.rs
test_module/spawn.js
test_module/src/lib.rs

Maybe we should setup a test framework(js) and write more tests from now on?

feat(napi): try to impl is_date

---

README.md
napi/src/lib.rs
napi/src/task.rs
test_module/__test__/create-external.spec.js
test_module/src/lib.rs

resolve https://github.com/napi-rs/napi-rs/issues/74

feat(napi): implement create_external and get_value_external

---

napi/Cargo.toml
napi/build.rs
napi/src/lib.rs
napi/src/threadsafe_function.rs
test_module/Cargo.toml
test_module/__test__/example.txt
test_module/__test__/threadsafe_function.spec.js
test_module/__test__/tokio_readfile.spec.js
test_module/__test__/tsfn_error.spec.js
test_module/src/lib.rs

~This is a premature implementation for getting more comments.~

feat(napi): impl threadsafe function api

---

.eslintrc.yml
.github/workflows/napi3.yaml
package.json
src/artifacts.ts
src/build.ts
src/consts.ts
src/create-npm-dir.ts
src/debug.ts
src/index.ts
src/pre-publish.ts
src/spawn.ts
src/update-package.ts
src/utils.ts
src/version.ts
test_module/package.json
yarn.lock

Resolve https://github.com/napi-rs/napi-rs/issues/90

feat: powerful cli

---

build/src/lib.rs

Fix #180 
Instead of trying to write to `C:\Program Files`, which requires admin privilege, this PR creates a `.napi-rs` folder inside the current user's home directory to save the downloaded `node-{version}.lib` file.
It seems that `napi-sys` crate downloads and extracts `node-headers` files to `OUT_DIR`:
https://github.com/napi-rs/napi-rs/blob/master/sys/build.rs#L61
Do you think we should move them to `.napi-rs` folder too? Looks like node-gyp is doing just that.
Thanks!

refactor: build on Windows without admin privilege.

---

napi/src/env.rs
napi/src/js_values/arraybuffer.rs
napi/src/js_values/mod.rs
test_module/__test__/arraybuffer.spec.ts
test_module/src/arraybuffer.rs
test_module/src/lib.rs

close https://github.com/napi-rs/napi-rs/issues/68

fix(napi): arraybuffer implement

---

src/build.ts

Close https://github.com/napi-rs/napi-rs/issues/219

fix: wrong condition in build command

---

test_module/__test__/class.spec.ts
test_module/src/class.rs

Close https://github.com/napi-rs/napi-rs/issues/236

test: add env#wrap tests

---

build/Cargo.toml
build/src/lib.rs
build/src/macos.rs
build/src/windows.rs
napi/Cargo.toml
napi/build.rs
napi/src/lib.rs
napi/src/win_delay_load_hook.rs

This PR will add Electron support for Windows. I don't think any other platform has any significant hurdles, but I am unable to test this as I can only test on Windows.
Possibly closes #125.

Add Electron Support

---

.github/workflows/windows-i686.yml
README.md
napi-derive/src/lib.rs
napi/src/async_work.rs
napi/src/env.rs
napi/src/error.rs
napi/src/js_values/arraybuffer.rs
napi/src/js_values/bigint.rs
napi/src/js_values/buffer.rs
napi/src/js_values/function.rs
napi/src/js_values/string/mod.rs
napi/src/promise.rs
napi/src/threadsafe_function.rs

Close https://github.com/napi-rs/napi-rs/issues/284

feat(napi): support build on i686-pc-windows-msvc

---

napi/src/async_work.rs
napi/src/env.rs
napi/src/error.rs
napi/src/js_values/arraybuffer.rs
napi/src/js_values/function.rs
napi/src/js_values/mod.rs
napi/src/js_values/value_type.rs
napi/src/promise.rs
napi/src/status.rs
napi/src/threadsafe_function.rs
sys/src/lib.rs
test_module/__test__/napi4/threadsafe_function.spec.ts
test_module/src/napi4/mod.rs
test_module/src/napi4/tsfn.rs
test_module/src/tokio_rt/read_file.rs

/cc @adumbidiot 
Close https://github.com/napi-rs/napi-rs/issues/277
Close https://github.com/napi-rs/napi-rs/issues/272

feat(napi): impl Clone and Drop for ThreadSafeFunction, return Status  from ThreadSafeFunction::call

---

napi/src/env.rs
napi/src/js_values/mod.rs

Close https://github.com/napi-rs/napi-rs/issues/297

fix(napi): windows-i686 release build problem

---

napi-derive/src/lib.rs
napi/src/env.rs
napi/src/lib.rs

Close https://github.com/napi-rs/napi-rs/issues/311

fixx(napi): CString memory leak

---

napi/src/env.rs
napi/src/js_values/mod.rs
napi/src/js_values/value_ref.rs
test_module/__test__/napi4/threadsafe_function.spec.ts
test_module/src/napi4/mod.rs
test_module/src/napi4/tsfn.rs

Close https://github.com/napi-rs/napi-rs/issues/356

feat(napi): implement create_reference/get_reference_value

---

napi/src/async_work.rs
napi/src/task.rs
test_module/__test__/spawn.spec.ts
test_module/src/task.rs

Do some cleanup logic if needed
Close https://github.com/napi-rs/napi-rs/issues/369

feat(napi): provide reject method in Task trait

---

bench/Cargo.toml
bench/bench.ts
bench/buffer.ts
bench/src/buffer.rs
bench/src/lib.rs
bench/tsconfig.json
napi/src/env.rs

Close https://github.com/napi-rs/napi-rs/issues/371

fix(napi): memory issues in create_external_buffer

---

cli/src/build.ts

Close https://github.com/napi-rs/napi-rs/issues/376

Build enhancement

---

napi/src/env.rs
test_module/src/cleanup_env.rs
test_module/src/external.rs

Close https://github.com/napi-rs/napi-rs/issues/372

Size hint in external

---

napi/src/js_values/arraybuffer.rs
napi/src/js_values/buffer.rs
test_module/__test__/buffer.spec.ts
test_module/src/buffer.rs

Close https://github.com/napi-rs/napi-rs/issues/386

feat(napi): AsMut and DerefMut for JsBuffer

---

bench/bench.ts
bench/get-set-property.ts
bench/src/get_set_property.rs
bench/src/lib.rs

Related: https://github.com/Brooooooklyn/skia-rs/pull/115
All properties should get from native object directly

chore: add bench suite for object getter setter

---

napi/Cargo.toml
napi/src/promise.rs
napi/src/tokio_rt.rs

Close https://github.com/napi-rs/napi-rs/issues/397
Close https://github.com/napi-rs/napi-rs/issues/396

fix(napi): remove unexpected napi_acquire_threadsafe_function

---

napi/src/js_values/arraybuffer.rs
napi/src/js_values/bigint.rs
napi/src/js_values/boolean.rs
napi/src/js_values/mod.rs
napi/src/js_values/number.rs
napi/src/js_values/string/mod.rs
napi/src/js_values/undefined.rs

Close https://github.com/napi-rs/napi-rs/issues/411

fix(napi): remove into_*_ref from JsString

---

cli/src/create-npm-dir.ts
cli/src/new/index.ts

Close https://github.com/napi-rs/napi-rs/issues/423

fix(cli): mkdir -p is not valid command in powershell

---

cli/src/new/index.ts

Close https://github.com/napi-rs/napi-rs/issues/454

fix(cli): new command without npm scope

---

.github/workflows/docker.yaml

Test run: https://github.com/messense/napi-rs/actions/runs/704049080
Test image: https://github.com/users/messense/packages/container/package/napi-rs%2Fnodejs-rust

Build multiarch Docker images

---

napi-derive/src/lib.rs
napi/src/async_work.rs
napi/src/js_values/bigint.rs
napi/src/js_values/either.rs
napi/src/js_values/escapable_handle_scope.rs
napi/src/js_values/function.rs
napi/src/js_values/mod.rs
test_module/__test__/function.spec.ts
test_module/src/function.rs

Close https://github.com/napi-rs/napi-rs/issues/436

refactor(napi): split NapiRaw trait from NapiValue

---

napi/src/promise.rs

Fix https://github.com/napi-rs/napi-rs/issues/566

fix(napi): wrong memory location of data in future resolved callback

---

.eslintrc.yml
.github/workflows/memory-test.yml
Cargo.toml
bench/Cargo.toml
memory-testing/Cargo.toml
memory-testing/build.rs
memory-testing/index.mjs
memory-testing/package.json
memory-testing/serde.js
memory-testing/src/lib.rs
memory-testing/test-util.mjs
memory-testing/tokio-future.js
memory-testing/util.js
napi/src/env.rs
napi/src/js_values/de.rs
napi/src/js_values/ser.rs
napi/src/js_values/string/latin1.rs
napi/src/threadsafe_function.rs
package.json
test_module/__test__/arraybuffer.spec.ts
test_module/src/arraybuffer.rs
test_module/src/class.rs
test_module/src/lib.rs
test_module/src/serde.rs
tsconfig.root-lint.json
yarn.lock

Close https://github.com/napi-rs/napi-rs/issues/585

Perform memory testing in CI

---

cli/src/pre-publish.ts

Published `@napi-rs/cli@1.1.0-alpha.0`
Close https://github.com/napi-rs/napi-rs/issues/600

feat(cli): support skip gh-release in prepublish command

---

cli/src/build.ts
cli/src/utils.ts

Close https://github.com/napi-rs/napi-rs/issues/686

fix(cli): create dist dir if not existed while building

---

cli/package.json
cli/src/index.ts
cli/src/new/cargo-config.ts
cli/src/new/cargo.ts
cli/src/new/ci-template.ts
cli/src/new/ci-yml.ts
cli/src/new/index.ts
cli/src/new/indexjs.ts
cli/src/new/lib-rs.ts
cli/src/new/npmignore.ts
cli/src/new/package.ts
yarn.lock

Close https://github.com/napi-rs/napi-rs/issues/699

feat(cli): add back new command

---

napi/src/env.rs
test_module/__test__/env.spec.ts
test_module/src/env.rs

Close https://github.com/napi-rs/napi-rs/issues/833

feat(napi): implement Env::throw to throw any JsValue

---

crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/js_values/arraybuffer.rs
crates/napi/src/js_values/buffer.rs

feat(napi): refine return type

---

cli/src/build.ts

Close https://github.com/napi-rs/napi-rs/issues/936

fix(cli): disable js binding generation if no --platform flag

---

crates/backend/src/codegen/struct.rs
examples/napi/src/array.rs
examples/napi/src/class.rs
examples/napi/src/typed_array.rs

Close https://github.com/napi-rs/napi-rs/issues/949

fix(napi-derive): codegen bug when multi impl on same file

---

crates/napi/Cargo.toml
crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/tokio_runtime.rs
examples/napi/__test__/worker-thread.spec.ts
examples/napi/__test__/worker.js
examples/napi/package.json
examples/napi/src/typed_array.rs
yarn.lock

Close https://github.com/napi-rs/napi-rs/issues/943

Fix undefined module in worker_threads

---

crates/backend/src/codegen/enum.rs
crates/backend/src/codegen/fn.rs

Close https://github.com/napi-rs/napi-rs/issues/968

fix(napi-derive): ignore warnings on generated fn

---

cli/src/js-binding-template.ts

Ref: https://github.com/swc-project/swc/commit/1dfc2ee1054d20b0d04699ebef3ab09b2f6fc4f8

fix(cli): handle lld not found

---

crates/napi/src/async_work.rs
crates/napi/src/bindgen_runtime/error.rs
crates/napi/src/bindgen_runtime/js_values.rs
crates/napi/src/bindgen_runtime/js_values/array.rs
crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/bigint.rs
crates/napi/src/bindgen_runtime/js_values/boolean.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/js_values/either.rs
crates/napi/src/bindgen_runtime/js_values/external.rs
crates/napi/src/bindgen_runtime/js_values/map.rs
crates/napi/src/bindgen_runtime/js_values/nil.rs
crates/napi/src/bindgen_runtime/js_values/number.rs
crates/napi/src/bindgen_runtime/js_values/promise.rs
crates/napi/src/bindgen_runtime/js_values/serde.rs
crates/napi/src/bindgen_runtime/js_values/string.rs
crates/napi/src/bindgen_runtime/js_values/symbol.rs
crates/napi/src/bindgen_runtime/js_values/task.rs
crates/napi/src/bindgen_runtime/mod.rs
crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/env.rs
crates/napi/src/error.rs
crates/napi/src/js_values/bigint.rs
crates/napi/src/js_values/mod.rs
crates/napi/src/js_values/object.rs
crates/napi/src/lib.rs
crates/napi/src/promise.rs
crates/napi/src/threadsafe_function.rs
crates/napi/src/win_delay_load_hook.rs

https://github.com/napi-rs/napi-rs/issues/1022#issuecomment-1011059923

chore: forbid unsafe_op_in_unsafe_fn

---

cli/src/build.ts

For [this example](https://github.com/napi-rs/napi-rs/tree/main/examples/napi)
Without `--strip`
```bash
❯ ls -lrth index.node
-rwxr-xr-x  1 messense  staff   5.1M Jan 13 16:59 index.node
```
With `--strip`
```bash
❯ ls -lrth index.node
-rwxr-xr-x  1 messense  staff   1.9M Jan 13 16:59 index.node
```

feat(cli): add `--strip` option for removing symbols

---

cli/src/build.ts

Fixes https://github.com/yisibl/resvg-js/pull/47

fix(cli): properly handle RUSTFLAGS env var

---

crates/napi/src/threadsafe_function.rs

This fixes a deadlock/panic in Electron when the window is reloaded. See #1021 and the comments below.

fix(napi): abort threadsafe functions upon env cleanup

---

crates/napi/src/async_work.rs
crates/napi/src/js_values/value_ref.rs
crates/napi/src/promise.rs

- Fix https://github.com/napi-rs/napi-rs/issues/1028

fix(napi): clippy error on 1.58

---

.github/workflows/zig.yaml
cli/package.json
cli/src/index.ts
rollup.config.js
yarn.lock

Close https://github.com/napi-rs/napi-rs/issues/1059

fix(cli): compatible for Node.js 10x

---

.cirrus.yml
.github/workflows/android-armv7.yml
.github/workflows/android.yml
.github/workflows/asan.yml
.github/workflows/bench.yaml
.github/workflows/lint.yaml
.github/workflows/linux-aarch64-musl.yaml
.github/workflows/linux-aarch64.yaml
.github/workflows/linux-armv7.yaml
.github/workflows/linux-musl.yaml
.github/workflows/memory-test.yml
.github/workflows/test.yaml
.github/workflows/windows-arm.yml
.github/workflows/windows-i686.yml
.github/workflows/zig.yaml
ava.config.mjs
cli/src/new/ci-template.ts
crates/backend/src/codegen/fn.rs
crates/backend/src/codegen/struct.rs
crates/napi/src/bindgen_runtime/callback_info.rs
crates/napi/src/bindgen_runtime/js_values/number.rs
crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/js_values/de.rs
crates/napi/src/js_values/mod.rs
crates/napi/src/tokio_runtime.rs
examples/napi/__test__/worker-thread.spec.ts
examples/napi/src/callback.rs
package.json

Close https://github.com/napi-rs/napi-rs/issues/1073

fix(napi): race issues with Node.js worker_thread

---

crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/mod.rs

Close https://github.com/napi-rs/napi-rs/issues/1124

chore(napi): show tips if create different buffers with same data

---

crates/napi/src/env.rs

unrwap -> unwrap

---

crates/backend/src/typegen/fn.rs
crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/env.rs
examples/napi-compat-mode/__test__/buffer.spec.ts
examples/napi/__test__/values.spec.ts

Close https://github.com/napi-rs/napi-rs/issues/1146

fix(napi): use create_buffer/arrary_buffer if provided data is empty

---

crates/backend/Cargo.toml
crates/build/Cargo.toml
crates/macro/Cargo.toml
crates/napi/Cargo.toml
crates/sys/Cargo.toml

https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
Ref https://github.com/napi-rs/napi-rs/issues/1184

Add `rust-version` field to `Cargo.toml`s

---

crates/napi/src/threadsafe_function.rs

- Close https://github.com/napi-rs/napi-rs/issues/1220
@SevInf I can confirm this can fix the memory leak issue in your repro repo, could you try it in the Prisma engine?

fix(napi): memory leak in ThreadsafeFunction

---

crates/napi/src/threadsafe_function.rs
memory-testing/index.mjs
memory-testing/src/lib.rs
memory-testing/tsfn.mjs

- Close https://github.com/napi-rs/napi-rs/issues/1220

fix(napi): use Mutex instead of Atomic in ThreadsafeFunction

---

crates/backend/src/codegen/fn.rs

Follow up of https://github.com/napi-rs/napi-rs/issues/1218.
This patch fixes https://github.com/napi-rs/napi-rs/issues/1237.
`#[napi(strict)]` was implemented for arguments of kind `T`, but not for `&T` nor `&mut T`. This patch fixes that by type checking the missing patterns.

feat(backend) Support `#[napi(strict)]` on `&T` and `&mut T`

---

crates/backend/src/codegen/struct.rs

Fix: #1277
Add alias to the field ident, so that field name won't shadow some variable during macro expansion

fix(napi-derive): fix macro expansion naming shadow

---

.github/workflows/docker.yaml
.github/workflows/linux-musl.yaml
.github/workflows/zig.yaml

Fixes broken CI for a forked repo.

chore: fix ci for forked repo

---

cli/src/build.ts

fix: custom Cargo (build) target directories

---

.cirrus.yml

https://cirrus-ci.org/guide/macOS/

Add arm64 macOS CI

---

cli/src/new/package.ts

- Close https://github.com/napi-rs/napi-rs/issues/1312

chore(cli): increase ava timeout

---

cli/src/build.ts

Alternative approach to #1329.
Closes #1328 
Closes #1329

feat(cli): parse `Cargo.toml` using `cargo metadata`

---

crates/napi/src/bindgen_runtime/js_values/bigint.rs

fix(napi): BigInt::get_u64 lossless check

---

crates/napi/src/bindgen_runtime/js_values/string.rs
crates/napi/src/error.rs
examples/napi/__test__/values.spec.ts

- Close https://github.com/napi-rs/napi-rs/issues/1264

chore(napi): including type message in error message

---

cli/src/help.ts
cli/src/index.ts

napi-cli support -h/--help command

fix(cli): support help command

---

cli/src/update-package.ts
cli/src/utils.ts

fix(cli): incorrent version without npm folder

---

crates/napi/src/async_work.rs

The third argument to `napi_create_async_work` (async_resource_name) should be a `napi_value` that corresponds to a null-terminated utf-8 string.
This resolves errors running Next.js with GraalVM.
oracle/graal#5582
oracle/graal#5581

fix(napi): napi_create_async_work incorrect argument (napi-rs#1392)

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs

- Close https://github.com/napi-rs/napi-rs/issues/1421

fix(napi): array buffer drop notify never be called in cloned buffer

---

crates/napi/src/threadsafe_function.rs
examples/napi/src/threadsafe_function.rs

- Close https://github.com/napi-rs/napi-rs/issues/1441

fix(napi): remove useless aquire while creating ThreadsafeFunction

---

cli/src/new/ci-template.ts

Tested in https://github.com/Brooooooklyn/napi-rs-cli-testing/actions/runs/4072272583/jobs/7014916027

chore(cli): upgrade cross platform testing toolchains

---

cli/src/build.ts

fix(cli): JS bindgen file now respects destDir

---

crates/napi/src/threadsafe_function.rs

Because the life cycle of tsfn-raw is bound to node env, so we can add tsfn-raw to cleanup hook as well.

fix(napi):  prevent access to tsfn-raw after env's destroyed(#1514)

---

cli/src/build.ts

@suyanhanx can you review this pull request?
- Close https://github.com/napi-rs/napi-rs/issues/1523

fix(cli): dts pipe

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs

- Close https://github.com/napi-rs/napi-rs/issues/1544

fix(napi): use ptr::copy to create TypedArray in electron fallback mode

---

cli/src/js-binding-template.ts

chore: fix js binding template style

---

crates/napi/src/bindgen_runtime/js_values/value_ref.rs
crates/napi/src/bindgen_runtime/mod.rs
examples/napi/__tests__/worker-thread.spec.ts
examples/napi/__tests__/worker.js
package.json

- Close https://github.com/napi-rs/napi-rs/issues/1560

fix(napi): thread safe issue while creating class instance

---

crates/backend/src/codegen/fn.rs
crates/napi/src/bindgen_runtime/callback_info.rs

- Close https://github.com/napi-rs/napi-rs/issues/1575

fix(napi-derive): increase initial ref count in async fn

---

crates/napi/src/js_values/bigint.rs
crates/napi/src/js_values/de.rs

Hi!
This PR does the following:
* Handle little endianness;
* Make sure get_<u/i>128 methods don't panic when words.len() < 2;
* Make sure BigInt deserialization takes into account word length and sign;
For context:
I'm using `napi-rs` in a context where I need to deserialize random Typescript values into concrete Rust types that I can't control. So I get a `BigInt`, which I need to deserialize into u64. With the current `napi-rs` version, deserialization would panic if a `BigInt` is provided that fits into a single word. With this change the rust type `napi-rs` deserializes `BigInt` into depends on what the value actually holds in memory on node side. Also, node API docs outline that the words are little endian, but this wasn't handled in the current implementation, so added that too! …

feat(napi): Bigint deserialization

---

crates/napi/src/bindgen_runtime/js_values/buffer.rs

Hey!
Thank you for the project. This would be nice to have for deriving Default on structs that have `Buffer` in them.

feat(napi): impl Default for Buffer

---

crates/napi/src/env.rs
crates/napi/src/error.rs
crates/sys/src/functions.rs

- Close https://github.com/napi-rs/napi-rs/issues/1600

feat(napi,sys): sync to napi9

---

cli/src/api/templates/js-binding.ts

- Close https://github.com/napi-rs/napi-rs/issues/1775

fix(cli): js binding template

---

crates/build/src/lib.rs
crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/tokio_runtime.rs

- Close https://github.com/napi-rs/napi-rs/issues/1719

fix(build): rerun if cli version changed

---

.github/workflows/test-release.yaml
crates/build/src/wasi.rs
crates/napi/src/bindgen_runtime/js_values/task.rs
crates/napi/src/tokio_runtime.rs
examples/napi/__tests__/generator.spec.ts
examples/napi/__tests__/object-attr.spec.ts
examples/napi/__tests__/strict.spec.ts
examples/napi/__tests__/values.spec.ts
examples/napi/__tests__/worker-thread.spec.ts
examples/napi/__tests__/worker.cjs

Pass the rest of async tests, including await the JavaScript Promise in the Rust side, and the worker_threads tests.

feat(napi): pass the rest of async tests

---

.github/workflows/docker.yaml
alpine-zig.Dockerfile
debian-aarch64.Dockerfile
debian-zig.Dockerfile
debian.Dockerfile

build: upgrade toolchain in Docker

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/module_register.rs

- Close https://github.com/napi-rs/napi-rs/issues/1800

fix(napi): cargo doc build

---

.cargo/config.toml
crates/backend/src/codegen/const.rs
crates/backend/src/codegen/enum.rs
crates/backend/src/codegen/fn.rs
crates/backend/src/codegen/struct.rs
crates/macro/src/lib.rs
crates/napi/Cargo.toml
crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/mod.rs
crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/env.rs
crates/napi/src/tokio_runtime.rs
examples/napi/Cargo.toml
examples/napi/src/async.rs

- Close https://github.com/napi-rs/napi-rs/issues/1816

fix(napi): compile error for wasm32-unknown-unknown target

---

cli/src/api/new.ts

fix(cli): throws if target path of new command test fails

---

debian-aarch64.Dockerfile
debian.Dockerfile

- Close https://github.com/napi-rs/napi-rs/issues/1840

ci: add back pnpm to debian Docker images

---

cli/src/api/templates/js-binding.ts

I forgot to update the binding template in #1599

fix(binding): add riscv64 linux binding

---

cli/codegen/commands.ts
cli/docs/artifacts.md
cli/docs/build.md
cli/src/def/artifacts.ts
cli/src/def/build.ts

https://github.com/napi-rs/napi-rs/pull/1850 was not fixed the problem
because the default value is codegen from cli/codegen/commands.ts

fix(cli): artifacts default option value

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/env.rs

- Close https://github.com/napi-rs/napi-rs/issues/1919

fix(napi): memory issue while creating external buffer on electron

---

crates/backend/src/codegen/fn.rs
crates/backend/src/codegen/struct.rs
crates/napi/src/bindgen_runtime/callback_info.rs
crates/napi/src/bindgen_runtime/js_values/value_ref.rs

- Close https://github.com/napi-rs/napi-rs/issues/1952

fix(napi): memory leak while using Reference

---

crates/napi/src/threadsafe_function.rs

For many reasons, in an app we can end up in a scenario where the thread / task that initially called the ThreadsafeFunction gets interrupted. This means that the receiver would get collected, should a ThreadsafeFunction be awaited on the said thread. This will create an error when the ThreadsafeFunction's callback will be called, and call a napi_fatal_error.
This change makes it so that if the send errors, this error is hidden and thus prevents any hard failure. If a ThreadsafeFunction is called in such a case, its output won't be used, but we'll still run all the logic to ensure it ran properly.
Fixes https://github.com/napi-rs/napi-rs/issues/1665 - cc @Brooooooklyn

fix(napi): no hard fail on ThreadsafeFunction::call_async

---

bench/src/get_set_property.rs
crates/napi/src/bindgen_runtime/js_values/external.rs
crates/napi/src/env.rs
examples/napi-compat-mode/src/class.rs
examples/napi-compat-mode/src/napi4/tsfn_dua_instance.rs
examples/napi/__tests__/values.spec.ts
examples/napi/src/external.rs
examples/napi/src/fn_strict.rs

- Close https://github.com/napi-rs/napi-rs/issues/1994

fix(napi): External should impl FromNapiRef rather than FromNapiValue

---

.github/workflows/zig.yaml
cli/src/__test__/parse-triple.spec.ts
cli/src/build.ts
cli/src/js-binding-template.ts
cli/src/new/ci-template.ts
cli/src/new/index.ts

feat(target): add support for armv7-unknown-linux-muslebihf

---

crates/macro/src/parser/mod.rs
examples/napi/tests/build_error_tests/fn_outside_impl_factory.rs
examples/napi/tests/build_error_tests/fn_outside_impl_factory.stderr
examples/napi/tests/build_error_tests/mod.rs
examples/napi/tests/macro_tests.rs

- Close https://github.com/napi-rs/napi-rs/issues/2048

fix(napi-derive): bail the unexpected factory directive

---

examples/napi/example.wasi-browser.js
wasm-runtime/fs-proxy.cjs
wasm-runtime/package.json
yarn.lock

allow sync fs operation between workers/mainThread

---

cli/src/api/build.ts

Related issue: 
https://github.com/launchbadge/sqlx/issues/3277
https://github.com/briansmith/ring/issues/897

fix(cli): rename env CC to TARGET_CC avoid proc-macro build failed

---

crates/napi/src/bindgen_runtime/js_values.rs

fix: https://github.com/ohos-rs/ohos-rs/actions/runs/9888517751/job/27313248629?pr=47

fix(napi): re-export feature should be align

---

crates/backend/src/codegen.rs
crates/backend/src/codegen/struct.rs
crates/macro/src/parser/mod.rs

fix: napi getter macros

---

crates/backend/src/codegen/struct.rs

fix: missing impl for FromNapiValue due to object_from_js being false

---

crates/macro/src/parser/mod.rs

closes https://github.com/napi-rs/napi-rs/issues/1668

fix(napi-derive): replace self when function returns `Result<Self>`

---

crates/macro/src/expand/napi.rs

Related PR: https://github.com/napi-rs/napi-rs/pull/2195

fix(napi-derive): call flush on the BufWriter

---

.github/workflows/test-release.yaml
crates/backend/Cargo.toml
crates/backend/src/codegen.rs
crates/backend/src/codegen/const.rs
crates/backend/src/codegen/enum.rs
crates/backend/src/codegen/fn.rs
crates/backend/src/codegen/struct.rs
crates/build/Cargo.toml
crates/macro/Cargo.toml
crates/macro/src/expand.rs
crates/macro/src/expand/napi.rs
crates/macro/src/parser/attrs.rs
crates/napi/Cargo.toml
crates/napi/src/bindgen_runtime/js_values/class.rs
crates/napi/src/bindgen_runtime/mod.rs
crates/napi/src/bindgen_runtime/module_register.rs
crates/sys/Cargo.toml
examples/napi/src/class.rs

- Close https://github.com/napi-rs/napi-rs/issues/944

refactor(napi-derive): expand order

---

examples/napi/__tests__/strict.spec.ts

Fix the case problem related to date found according to the unit test results of OpenHarmony.

test: fix some test case

---

crates/backend/src/codegen/struct.rs

I have implemented these in reverse. 🤦
refs #2376

fix(napi-derive): object_from_js / object_to_js for transparent was swapped

---

cli/src/api/build.ts

If the user does not set dtsCache, set the default value to true. If the user sets dtsCache, use the user setting

fix(cli): set the default value of dtsCache to true

---

cli/src/api/templates/js-binding.ts

fix https://github.com/napi-rs/napi-rs/issues/2468

feat(cli): allow specifing native library path via env variable

---

.github/workflows/asan.yml
.github/workflows/test-release.yaml

Ref: https://github.com/actions/runner-images/issues/11471

ci: pin qemu and ubuntu version

---

cli/src/api/templates/js-binding.ts
examples/napi/index.cjs

- Ref https://github.com/web-infra-dev/rspack/issues/9798#issuecomment-2756165635

chore(cli): excludeNetwork on getting report

---

wasm-runtime/fs-proxy.cjs
wasm-runtime/fs-proxy.test.cjs
wasm-runtime/package.json

fix(wasm-runtime): wasm fs proxy serialization

---

wasm-runtime/package.json
yarn.lock

fixes https://github.com/toyobayashi/emnapi/pull/144

fix(wasm-runtime): upgrade emnapi

---

wasm-runtime/fs-proxy.cjs

fix(wasm-runtime): fs-proxy test failed on s390x platform

---

crates/macro/src/expand/napi.rs
crates/macro/src/parser/attrs.rs
examples/napi/Cargo.toml
examples/napi/src/class.rs

- Close https://github.com/napi-rs/napi-rs/issues/2635
- Close https://github.com/napi-rs/napi-rs/issues/2602
- Close https://github.com/napi-rs/napi-rs/issues/1194

fix(napi-derive): #[cfg_attr(feature = "xxx", napi)]

---

crates/napi/src/bindgen_runtime/js_values/stream/read.rs

- Close https://github.com/napi-rs/napi-rs/issues/2604

fix(napi): cleanup inner Stream when complete

---

crates/macro/src/expand/napi.rs
crates/napi/src/bindgen_runtime/js_values/stream/read.rs
crates/napi/src/bindgen_runtime/mod.rs
crates/napi/src/error.rs
crates/napi/src/js_values/deferred.rs
crates/napi/src/threadsafe_function.rs
examples/napi/src/error.rs
examples/napi/src/stream.rs

- Close https://github.com/napi-rs/napi-rs/issues/1640

fix!(napi): unsound issues in Error

---

crates/napi/src/bindgen_runtime/js_values/object.rs

- Close https://github.com/napi-rs/napi-rs/issues/2641

chore(napi): make Object::from_raw pub

---

crates/napi/src/async_work.rs
crates/napi/src/bindgen_runtime/js_values/function.rs
crates/napi/src/bindgen_runtime/js_values/task.rs
crates/napi/src/env.rs
examples/napi/__tests__/values.spec.ts
examples/napi/electron.cjs

- Close https://github.com/napi-rs/napi-rs/issues/2141

fix(napi): reuse issue on AbortSignal

---

crates/napi/Cargo.toml
crates/napi/src/bindgen_runtime/js_values/value_ref.rs
crates/napi/src/bindgen_runtime/module_register.rs

I think using fx hash and no hash hasher will be fast than default hash hasher.

perf(napi): hash map by fx hash and no hash hasher

---

.github/workflows/test-release.yaml
cli/src/utils/misc.ts

- Close https://github.com/napi-rs/napi-rs/issues/2692

fix(cli): remove `require` in utils

---

crates/napi/src/bindgen_runtime/js_values/object.rs
crates/napi/src/bindgen_runtime/js_values/serde.rs
crates/napi/src/js_values/object_property.rs

- Close https://github.com/napi-rs/napi-rs/issues/2696

fix(napi): memory leak in Object Property

---

cli/esbuild.mjs
cli/src/api/templates/js-binding.ts
cli/src/utils/log.ts
examples/napi-compat-mode/__tests__/napi6/bigint.spec.ts
examples/napi-compat-mode/index.wasi.cjs
examples/napi-compat-mode/wasi-worker-browser.mjs
examples/napi-compat-mode/wasi-worker.mjs
examples/napi/index.cjs

chore(cli): link npm cli issues in native binding load errors
run fmt

chore(cli): link npm cli issues in native binding load errors

---

crates/napi/src/bindgen_runtime/js_values/object.rs

Ref: https://github.com/napi-rs/napi-rs/pull/2711

fix(napi): avoid allocate empty Box if closures is empty

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs

- Close https://github.com/napi-rs/napi-rs/issues/2719

fix(napi): wrong drop impl for TypedArray::with_external_data

---

cli/e2e/cli.spec.ts
cli/src/utils/config.ts

- Close https://github.com/napi-rs/napi-rs/issues/2728

fix(cli): throw error if targets are duplicated

---

crates/build/src/wasi.rs

If I understand the code correctly...

fix(build): increase wasi stack size

---

examples/napi/__tests__/values.spec.ts

Added a bit more tests for #2829

test(napi): add more tests for `Error.cause` support

---

wasm-runtime/package.json

fix(wasm-runtime): publish `dist/*.cjs`

---

.github/workflows/test-release.yaml
Cargo.toml
crates/backend/src/codegen/const.rs
crates/backend/src/codegen/enum.rs
crates/backend/src/codegen/fn.rs
crates/backend/src/codegen/struct.rs
crates/macro/src/expand/typedef.rs
crates/macro/src/expand/typedef/type_def.rs
crates/macro/src/lib.rs
crates/macro/src/parser/mod.rs
crates/napi/src/error.rs
examples/napi-cargo-test/Cargo.toml
examples/napi-cargo-test/src/lib.rs

- Close https://github.com/napi-rs/napi-rs/issues/2871

fix(napi): link issue on cargo test --features noop

---

cli/src/api/__tests__/build.spec.ts
cli/src/api/__tests__/create-npm-dirs.spec.ts
cli/src/api/__tests__/new.spec.ts
cli/src/api/build.ts
cli/src/cli.ts
cli/src/index.ts

- Close https://github.com/napi-rs/napi-rs/issues/2709

feat(cli): export more build apis

---

cli/cli.mjs
cli/package.json
cli/src/api/__tests__/build.spec.ts
cli/tsdown.config.ts
yarn.lock

- Close https://github.com/napi-rs/napi-rs/issues/2940

fix(cli): bundle empathic
