napi/src/js_values/buffer.rs
napi/src/js_values/function.rs
napi/src/js_values/mod.rs
napi/src/threadsafe_function.rs
test_module/__test__/function.spec.js
test_module/__test__/threadsafe_function.spec.js
test_module/src/function.rs
test_module/src/lib.rs
test_module/src/tsfn.rs

Just found that `ctx.get::<Function>(0)` is not implemented in the previous version. 
`JsFunction::call()` accept `JsUnknown` as its arguments but it seems that there is no simple way to create a `JsUnknown` from other js types, like `JsString` in the example. We might want to add a api for that?

chore: add into_unknown; refactor tsfn api; add tests for js function

---

napi/src/threadsafe_function.rs

Hello,
This fixes the inline documentation to match the current API of threadsafe functions, since the number of arguments is no longer passed as a u64, but inferred from the length of the Vector.
It also adds notes about the intended argument convention, passing an Error or null as the first argument depending on the Result.
https://nodejs.org/en/knowledge/errors/what-are-the-error-conventions/
Thanks!
Closes #107

Fixed documentation of threadsafe functions

---

napi/src/env.rs
test_module/__test__/napi4/uv.spec.js
test_module/__test__/napi4/uv_worker.js

Using the`uv_loop_s` from `napi_env` is safer as it's possible that
there are multiple Workers, and therefore multiple uv_loop_s.

refactor(napi): use get_uv_event_loop instead of uv_default_loop

---

sys/build.rs

It's cumbersome to use the api from `uv.h` as we have to assign values of each fields for `structs` manually. 
`derive_default(true)` would help a lot(although providing api from `uv.h` might not be what `napi-rs` want to deliver).

chore: make bindgen::Builder derive default

---

napi/src/js_values/arraybuffer.rs
napi/src/js_values/mod.rs
napi/src/js_values/object.rs
napi/src/js_values/object_property.rs
napi/src/js_values/value_type.rs
napi/src/status.rs
sys/build.rs

Fixes #277. I switched from `rustifed_enum` to `newtype_enum` in `bindgen`. I then replaced all instances of `From` with `TryFrom` where applicable. The conversion uses the library error type with only a status of `Status::Unknown`, which I thought fit here. I will edit if changes are needed.

Convert bindgen `rustified_enum` to `newtype_enum`

---

napi-derive/src/lib.rs
napi/src/async_work.rs
napi/src/call_context.rs
napi/src/env.rs
napi/src/js_values/arraybuffer.rs
napi/src/js_values/bigint.rs
napi/src/js_values/buffer.rs
napi/src/js_values/de.rs
napi/src/js_values/either.rs
napi/src/js_values/function.rs
napi/src/js_values/global.rs
napi/src/js_values/mod.rs
napi/src/js_values/object_property.rs
napi/src/js_values/ser.rs
napi/src/lib.rs
test_module/src/class.rs
test_module/src/function.rs
test_module/src/object.rs

Close https://github.com/napi-rs/napi-rs/issues/300
Close https://github.com/napi-rs/napi-rs/issues/299

fix(napi): CString issues

---

napi/src/threadsafe_function.rs
test_module/__test__/napi4/threadsafe_function.spec.ts
test_module/__test__/napi4/tsfn-throw.js

```
Error: Throw in thread safe function
at /Users/longyinan/workspace/github/napi-rs/test_module/__test__/napi4/tsfn-throw.js:4:9
```
Close https://github.com/napi-rs/napi-rs/issues/437

fix(napi): throw out raw JavaScript error in tsfn

---

napi-derive/src/lib.rs
napi/src/call_context.rs
napi/src/env.rs
napi/src/js_values/object.rs
napi/src/js_values/value_ref.rs

Preview of the mainly added function (under `impl Env`):
While doing this, I found the `arg_len` parameter in `CallContext::new()` to be redundant (and thus even dangerous, should it end up different to the len of the vec), so I've also taken the liberty of trimming that part (adapting the derive accordingly).
Finally, two nits I've spotted when working with this crate: the `ref_count` parameter of `Ref`'s constructor was not used for the actual construction, and also there is an issue with the `maybe_ref` usage in `object.rs` I haven't fixed that one since I wasn't dealing with that part of the API yet, but I thought it best to at least add a comment warning about it).

Add a way to convert stateful (Rust) closures into `JsFunction`s.

---

napi/src/threadsafe_function.rs
test_module/__test__/napi4/threadsafe_function.spec.ts
test_module/__test__/napi4/tsfn-dua-instance.js
test_module/__test__/napi4/tsfn_error.spec.ts
test_module/src/lib.rs
test_module/src/napi4/mod.rs
test_module/src/napi4/tsfn_dua_instance.rs

Before fix:
```
napi4 › threadsafe_function.ts › tsfn dua instance
test_module/__test__/napi4/threadsafe_function.spec.ts:95
94:   }                                                            
95:   t.notThrows(() => {                                          
96:     execSync(`node ${join(__dirname, 'tsfn-dua-instance.js')}`)
Function threw:
Error {
output: [
null,
Buffer @Uint8Array [],
Buffer @Uint8Array [],
],
pid: 26327,
signal: 'SIGABRT',
status: null,
stderr: Buffer @Uint8Array [],
stdout: Buffer @Uint8Array [],
message: 'Command failed: node /Users/longyinan/workspace/github/napi-rs/test_module/__test__/napi4/tsfn-dua-instance.js',
}
› test_module/__test__/napi4/threadsafe_function.spec.ts:96:5
› test_module/__test__/napi4/threadsafe_function.spec.ts:95:5
─
1 test failed
```
Close …

fix(napi): do not call release tsfn in Drop when ref count is 0

---

build/Cargo.toml
build/src/lib.rs

I ran into some issues cross compiling from macos to x86_64-unknown-linux-gnu. 
The current compile time checks don't work well for this as the build script is always compiled for the host, so the Mac linker args were getting set for a linux build.
This PR moves the check to the build script's runtime, ie the library compile time

Check compile target at runtime in build

---

cli/README.md
cli/src/build.ts

For CI it's sometimes very useful to have an environment variable for the target.
Also noticed the cwd flag existed and added it to the readme

Add docs and target env variable to napi/cli

---

README.md

It has been renaned, see also:
https://nodejs.medium.com/renaming-n-api-to-node-api-27aa8ca30ed8

readme: fix references to Node-API after its renaming

---

napi/src/js_values/string/utf16.rs
napi/src/js_values/string/utf8.rs
rustfmt.toml

The utf8 and utf16 values leak memory a lot, if we don't handle the `ManuallyDrop` values. This fix is first try of changing it. I'd remove the `ManuallyDrop` values completely, but I don't know are they actually needed elsewhere in the code.
Closes: https://github.com/napi-rs/napi-rs/issues/581

Allow dropping of string&buffer values when converting

---

napi/src/js_values/string/mod.rs
napi/src/js_values/string/utf16.rs
napi/src/js_values/string/utf8.rs

Close https://github.com/napi-rs/napi-rs/issues/583
Don't know why I was using the `ManuallyDrop` in the previous approach, but it's definitely a wrong way to handle `JsString` value. Maybe I want to use `ManuallyDrop` to avoid data copied from `JsString` <=> `JsStringUtf8`, but there is no way to recycle the memory on *GC*.

fix(napi): JsString* leak in from_js_value

---

crates/backend/src/codegen/enum.rs
crates/backend/src/codegen/fn.rs
crates/backend/src/codegen/struct.rs
examples/napi/src/array.rs
examples/napi/src/class.rs
examples/napi/src/class_factory.rs
examples/napi/src/nullable.rs
examples/napi/src/number.rs

Fixes #850 
Could some of the types in `napi::bindgen_prelude` now be moved elsewhere to keep the prelude smaller?
For example, would `ctor` or `___CALL_FROM_FACTORY` ever be used by `napi` users, or were they only in the prelude for use in generated code?

Fully qualify all types in generated code

---

crates/build/src/lib.rs

The `rerun-if-changed` command expects a path, but as these are env vars (and the path `./TYPE_DEF_TMP_PATH` doesn't exist), this re-runs the build script every time. This PR fixes this and uses `rerun-if-env-changed` instead
https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-env-changedname

Fix cargo:rerun-if commands

---

crates/napi/src/env.rs
crates/napi/src/error.rs
crates/sys/src/lib.rs

Since the new added APIs are still experimental, I've added them under the `experimental` feature flag.

Enable node_api syntax error experimental functions

---

crates/napi/src/bindgen_runtime/js_values/external.rs
examples/napi/src/external.rs

Support External Value DeRef 
```
*external.as_ref() -> *external
```

feat(napi): support external deref

---

cli/src/build.ts
crates/build/src/lib.rs

fix: keep `.d.ts` and `.js` untouched if native doesn't change

---

.github/workflows/linux-aarch64-zig.yaml
cli/package.json
cli/src/build.ts
cli/src/parse-triple.ts
yarn.lock

https://actually.fyi/posts/zig-makes-rust-cross-compilation-just-work/
So that you don't need to compile in a docker container.
Example:
```bash
❯ uname -a
Darwin m1.lan 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
messense in m1 in napi-rs/examples/napi on  zig is 📦 v0.1.0 via  v17.3.0 via 🦀 v1.57.0
❯ yarn run build --zig --target x86_64-unknown-linux-gnu
yarn run v1.22.17
$ node ../../cli/scripts/index.js build --js false --zig --target x86_64-unknown-linux-gnu
Finished dev [unoptimized + debuginfo] target(s) in 0.02s
✨  Done in 0.67s.
messense in m1 in napi-rs/examples/napi on  zig is 📦 v0.1.0 via  v17.3.0 via 🦀 v1.57.0
❯ file index.node
index.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), …
```

Add support for cross compilation with Zig

---

crates/macro/src/parser/mod.rs

To support structs like this one:
```rust
#[napi(object)]
pub struct Struct {
pub r#type: u32,
}
```

Unraw rust identifiers before sending it to js.

---

.github/workflows/docker.yaml
alpine-zig.Dockerfile
cli/src/build.ts

Add `lts-alpine-zig`  Docker image for building `GLIBC_2.17` compatible binary.
I've tried to build `GLIBC_2.17` compatible binary on `ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-zig` image. But it seems the binary is always linked with `GLIBC_2.18` symbols:
```
yarn build --target x86_64-unknown-linux-gnu --zig --zig-abi-suffix 2.17
objdump -T zig-cross.linux-x64-gnu.node
```
<details>
<summary>Symbols</summary>
zig-cross.linux-x64-gnu.node:     file format elf64-x86-64
DYNAMIC SYMBOL TABLE:
0000000000000000  w   D  *UND*	0000000000000000  Base        __gmon_start__
0000000000000000  w   D  *UND*	0000000000000000  Base        _ITM_deregisterTMCloneTable
0000000000000000  w   D  *UND*	0000000000000000  Base        _ITM_registerTMCloneTable
0000000000000000  w   DF *UND* …

Musl zig cross

---

crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/tokio_runtime.rs

The `arg` argument was unused and the `env` is now passed to the cleanup hook, such that it unregisters itself if the module is unloaded.
Due to https://github.com/nodejs/node/issues/5016 (and `dlclose` not being exposed) this doesn't fix anything critical, but it avoids a Node.js crash if the following is run:
```
require('./module.node');
delete require.cache[require.resolve('./module.node')];
require('./module.node');
```

fix(napi): cleanup registered hook upon unloading module with tokio_rt

---

cli/src/build.ts

The build command uses its `__dirname` inside `node_modules` as a temporary directory for writing type definitions, but this path may not be writable.
In my case, I have the cli as a dependency in a Yarn v3 project that also uses PnP, so the package lives in a ZIP file. My workaround for now is `yarn unplug @napi-rs/cli`, but this PR should be a more permanent fix.

fix(cli): temporary dts path may not be writable

---

crates/napi/src/env.rs

`napi_create_buffer` allocates, but so does `Vec::with_capacity`, so `Env::create_buffer` allocated twice then leaked the `Vec` allocation.
On top of this, a `JsBufferValue` was returned with an empty slice, because it was based on the `Vec` (which was empty, though with capacity). There was no way to extend the slice or otherwise access the full capacity, except to do a round-trip `buf.to_raw().into_value()` (so it'd base the new slice on `napi_get_buffer_info`).
Issue with this change is that `napi_create_buffer` allocates without initialization. I think technically we'd need a slice like `[MaybeUninit<u8>]` in cases like this. Alternatively we could zero the buffer for the user, but technically a user can also pass us a `Buffer.allocUnsafe()`, so then should `JsBufferValue` always …

fix(napi): double allocation in create_buffer

---

.github/workflows/cli-binary.yml
Cargo.toml
cli/src/build.ts
examples/binary/.gitignore
examples/binary/Cargo.toml
examples/binary/package.json
examples/binary/src/main.rs
package.json
yarn.lock

For https://github.com/napi-rs/napi-rs/discussions/1077
> It would be nice if n-api CLI supported binaries, since the rest of the tooling (artifacts, CI actions, etc) are still beneficial.
I think #1074 would also need this to distribute binaries on npm.

Add support for building binaries

---

cli/src/build.ts

Set `maxBuffer` to 10mb, cargo metadata may output
data more than 1mb(the nodejs default value).
Refs:
- https://github.com/napi-rs/napi-rs/issues/1116

fix: cargo metadata with large project

---

crates/backend/src/codegen/fn.rs
crates/backend/src/codegen/struct.rs
crates/backend/src/typegen/fn.rs
crates/napi/src/bindgen_runtime/callback_info.rs
crates/napi/src/bindgen_runtime/js_values/value_ref.rs
crates/napi/src/bindgen_runtime/mod.rs
examples/napi/src/reference.rs

- Reference now is inject by #[napi] macro
- Class Reference and underlaying data now have the same lifetime

feat(napi): redesign the Reference API

---

crates/napi/src/env.rs

fixes #1135 
This error occurs when
```toml
napi = { version="2", default-features = false, features = ["napi4"] }
```

fix(napi): `cannot find trait ToNapiValue` error

---

crates/napi/src/bindgen_runtime/module_register.rs
crates/sys/Cargo.toml
crates/sys/src/functions.rs
crates/sys/src/lib.rs

Ref: https://github.com/yisibl/resvg-js/pull/107
`#[ctor::ctor]` doesn't run on windows-i686, don't know why ...

fix(napi): load Node-API symbols manually on Windows

---

cli/src/build.ts

This opens doors for using [cargo-xwin](https://github.com/messense/cargo-xwin) to cross compiling for Windows MSVC targets, for example
```bash
CARGO=cargo-xwin yarn build --target x86_64-pc-windows-msvc
Compiling winapi v0.3.9
Compiling pin-project-lite v0.2.7
Compiling futures-sink v0.3.19
Compiling slab v0.4.5
Compiling pin-utils v0.1.0
Compiling futures-io v0.3.19
Compiling ryu v1.0.9
Compiling once_cell v1.9.0
Compiling num_cpus v1.13.1
Compiling cfg-if v1.0.0
Compiling itoa v1.0.1
Compiling lazy_static v1.4.0
Compiling futures-core v0.3.19
Compiling futures-task v0.3.19
Compiling libc v0.2.112
Compiling memchr v2.4.1
Compiling futures-channel v0.3.19
Compiling serde v1.0.132
Compiling futures-util v0.3.19
Compiling encoding_rs v0.8.30
Compiling serde_json v1.0.73
Compiling …
```

feat(cli): allow specifying an alternative cargo binary via `CARGO` env var

---

cli/src/__test__/parse-triple.spec.ts
cli/src/build.ts
cli/src/parse-triple.ts

This matches [how `cargo` does it](https://github.com/rust-lang/cargo/blob/f624095e1c98228a74a165ddb702078c0dd8b81e/src/cargo/util/rustc.rs#L57-L75) and it removed `rustup` requirement. On some platforms like OpenBSD, rustup is not supported.

Parse host target triple from `rustc -vV`

---

crates/napi/src/bindgen_runtime/js_values/array.rs

This patch is the sequel of https://github.com/napi-rs/napi-rs/pull/1195 where `ToNapiValue` and `FromNapiValue` are implemented for all `Vec<T>` where `T` is a 8 or 16 bits number.

feat(napi) Extend #1195 to `Vec<T>`.

---

crates/napi/Cargo.toml
crates/napi/src/bindgen_runtime/callback_info.rs
crates/napi/src/bindgen_runtime/js_values/value_ref.rs
crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/tokio_runtime.rs

This makes the code a little bit easier to read because it's not a macro. It also reduces the dependencies when tokio is used, as tokio already depends on once_cell but not lazy_static.

Replace lazy_static with once_cell

---

crates/napi/src/bindgen_runtime/js_values.rs

Sequel of https://github.com/napi-rs/napi-rs/pull/1223.
Fix this comment https://github.com/napi-rs/napi-rs/pull/1223.
Let's say we have a Rust function defined as:
```rust
#[napi(strict)]
pub fn foo(a: i32, b: Option<i32>) -> … { … }
```
Calling this function in JavaScript as so will work:
```javascript
foo(1, null)
```
but calling this function as so will not work:
```javascript
foo(1)
foo(1, undefined)
```
This patch fixes that, by recognizing `undefined` as `Option::None`.

fix(napi) `undefined` is recognized as a valid `None` for `Option<T>`

---

crates/napi/src/threadsafe_function.rs

This makes it possible to reuse the same value, e.g. when writing utility/helper functions.

Add derived traits to `ThreadsafeFunctionCallMode`

---

cli/src/new/ci-template.ts

Since a few days ago freebsd-vm [recommends using the latest major version v0](https://github.com/vmactions/freebsd-vm#:~:text=is%20the%20most-,recommended%20to%20use), which might be common for actions.

chore(napi): use recommended `vmactions/freebsd-vm@v0`

---

crates/backend/src/codegen/struct.rs
crates/napi/src/bindgen_runtime/callback_info.rs
crates/napi/src/bindgen_runtime/js_values/value_ref.rs

Usually happens while using ZST
- Close https://github.com/napi-rs/napi-rs/issues/1288

fix(napi): remove previous reference if value_ref existed

---

crates/backend/Cargo.toml
crates/macro/Cargo.toml

Fixes https://github.com/napi-rs/napi-rs/issues/1292
This format still allows the same range of versions greater than 1.0.61 according to the docs:  https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
1 is equal to >=1, <2
1.0 is equal to >=1, <2
1.0.61 is equal to >=1.0.61, <2

pin minimum usable version of dependency syn

---

crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/mod.rs

I'm not 100% sure if all these changes are correct, so please have a close look at the commit messages explaining them, and the associated issue #1295 for more context.
CC @Xaeroxe @jose-acevedoflores

Fix some of the unsoundness in `Buffer`

---

crates/napi/src/bindgen_runtime/js_values.rs
crates/napi/src/bindgen_runtime/js_values/promise.rs
crates/napi/src/env.rs
crates/napi/src/error.rs
crates/napi/src/js_values/function.rs
crates/napi/src/promise.rs
examples/napi-compat-mode/__test__/function.spec.ts
examples/napi-compat-mode/src/function.rs

This enables `napi::Error` to wrap an arbitrary JavaScript value, which may have been returned or thrown from a function. This is useful for functions that must return an `napi::Result`, but may have an error propagated from calling a JavaScript function. The support was partially already there for the Promise implementation, but I've extended it.
This also checks if an exception is pending after calling a JS function, and retrieves it with `napi_get_and_clear_last_exception`. This way, the pending exception isn't necessarily immediately thrown when returning from the native function, but can be passed elsewhere if needed (e.g. to an error callback). This is also important when calling JS functions outside the native call context (e.g. from a background thread).

Improve error propagation

---

crates/napi/src/bindgen_runtime/js_values/array.rs
crates/napi/src/bindgen_runtime/js_values/either.rs
crates/napi/src/bindgen_runtime/js_values/external.rs
crates/napi/src/js_values/de.rs

add support for Vec<(std::string::String, u16)> and so on ( fix https://github.com/napi-rs/napi-rs/issues/1319 )
impl Send for External
auto  AsRef for Either
`impl<T: 'static> From<T> for External<T>`

add support for Vec<(std::string::String, u16)> and some other small change

---

.github/workflows/msrv.yml
crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/mod.rs
examples/napi/src/typed_array.rs
memory-testing/buffer.mjs
memory-testing/src/lib.rs
memory-testing/test-util.mjs

- Close https://github.com/napi-rs/napi-rs/issues/1326

fix(napi): should also delete the reference while dropping the Buffer

---

cli/src/new/ci-template.ts

This has been [officially supported](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs).

Remove unused ci condition

---

crates/napi/src/tokio_runtime.rs

Why?
because there are times when you need to run an async function syncronously, like in a constructor function.
Sure you can always still expose an async static class method to create the object, but I think it would be good to have the option.

expose tokio runtime's block_on function

---

crates/napi/src/tokio_runtime.rs

This pr makes the spawn function return the join handle so it can be safely aborted when droping the object it is 
spawned for.
Without this I need to run the future in a different tokio runtime instance to avoid a segfault:
https://github.com/deltachat/napi-jsonrpc/commit/de561631680789cb1db59f3c5d4145da028a052d
More info on the issue: https://github.com/deltachat/napi-jsonrpc/issues/2
Basically I have an event receiving loop that is spawned when creating an account manager, but without this pr I'm not able to shutdown/abort the event loop safely resulting in a segfault when Nodejs garbage collects the object.

return join handle when spawning a tokio task

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
examples/napi-compat-mode/__test__/arraybuffer.spec.ts
examples/napi-compat-mode/src/arraybuffer.rs

Notice from the n-api docs that the data returned from `napi_get_typedarray_info` is already adjusted by the byte offset. https://nodejs.org/api/n-api.html#napi_get_typedarray_info
This means that when `as_ref`/`as_mut` apply the byte offset, the offset is in practice applied twice.
This wasn't caught in tests because no test tried to modify a typed array with a byte offset, and the test didn't us the typed array structs, only `JsTypedArray`. If you want, I can modify the rest of the functions in examples/napi-compt-mode/src/arraybuffers.rs and the matching tests, to test all typed arrays.
IMO the `byte_offset` field can be removed entirely from the struct, but I wanted to submit a minimal PR.

Bug fix: typed arrays ref shouldn't use offset.

---

crates/backend/src/codegen/fn.rs

Before, the JS error would only have `Any { .. }`

Better error message for `#[napi(catch_unwind)]`

---

cli/src/js-binding-template.ts

Fixes #1335, checking the path of `ldd` before trying to read it.
Thanks!!

fix template to works with nix

---

crates/napi/src/env.rs

Fix https://github.com/napi-rs/napi-rs/issues/1380

add "run_script" for "Env"

---

cli/src/__test__/parse-triple.spec.ts
cli/src/artifacts.ts
cli/src/create-npm-dir.ts
cli/src/index.ts
cli/src/js-binding-template.ts
cli/src/new/ci-template.ts
cli/src/new/ci-yml.ts
cli/src/new/index.ts
cli/src/new/package.ts
cli/src/parse-triple.ts
cli/src/universal.ts

**TLDR:** adds third 'universal' synthetic arch for macOS which combines x64/arm64 binaries into a universal binary and produces a single npm subdependency which is only tied to OS as opposed to OS/CPU combo.
I am using napi-rs to create native macOS extension for electron App. It was working fine when building electron bundle on x64 host for x64 target, but I am now switching to arm64 host while still building for x64 target. This doesn't work due to the way how npm resolves optional dependencies and there's no good way to install x64 optional dependency on arm64 host. So instead of hacking something to workaround this, I decided it would be better to have an option to build universal binaries in napi-rs. That way, I will be able to build for both x64 and universal targets on arm64.
- …

Darwin universal architecture

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/module_register.rs

For this scenario:
```rust
pub async fn send_buffer(buffer: Buffer) -> u32 {
tokio::task::spawn(async move { buffer.len() as u32 })
.await
.unwrap()
}
```
`Buffer` will be dropped in the other thread.

fix(napi): add back custom gc for Send Buffer

---

cli/src/build.ts

Fixes issue when tomlPath has a space in it
(N.b. Sorry if I didn't follow a PR template - this was done in the browser)

[Fix] Quote toml path

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
memory-testing/buffer.mjs
memory-testing/src/lib.rs

Fix for #1419.
Problem is that `Uint8Array::new` only records the length of the `Vec` it receives, and ignores the capacity.
When it recreates the `Vec` later in order to drop it, it is created with capacity equal to the length:
https://github.com/napi-rs/napi-rs/blob/83e157e101046f516b09de006b345d075bfb57bb/crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs#L109-L110
So if original `Vec` had a larger capacity, `capacity - length` bytes are leaked. The allocator is also called with a different layout from what the original `Vec` was created with, which may cause unknown consequences.
This PR just adds `data::shrink_to_fit()` before recording length of the Vec. This is the simplest solution, and since `Uint8Array::new` takes ownership of the `Vec`, I can't see much benefit of not …

Fix ArrayBuffer memory leak

---

cli/src/build.ts

I assume that in CLI's build command, env var `CARGO` is meant to tell it what `cargo` to use.
e.g. `CARGO=my-cargo napi build --release` should result in CLI executing `my-cargo build --release`.
At present, this doesn't work. It instead executes `cargo-xwin build --release` (and I'm on a Mac).
Assuming that's the purpose of the var, this PR fixes it.

Fix CARGO env var in `napi build`

---

cli/src/build.ts

This PR includes 2 fixes:
1. fix #1430
Zig wasn’t being activated when `--zig` is passed unless the build was also cross-platform. Under this PR, the `--zig` flag opts in to zig compilation regardless of platform.
3. fix #1431 
`--zig-abi-suffix` was completely broken (its value did not change the suffix passed to zig). Under this PR, it works.
This PR also adds a debug message to show when zig is activated, so that (in debug mode) the user can tell whether their program is being compiled with `zig` or with the default compiler tools, as well as what target `zig` will compile for.

Fix broken zig behaviors

---

crates/macro/src/lib.rs

closes Fix a macro expand issue where the compiler complains `napi` is not a non-macro attribute if feature is set to `noop`.
```rust
#[napi(object)]
struct Foo {
#[napi(some_arguments)]
^^^^ not a non-macro attribute
bar: bool
}
```
closes https://github.com/napi-rs/napi-rs/issues/1271

fix(napi-derive): remove ts type on field attrs for feature `noop`

---

crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/sys/src/types.rs
package.json
yarn.lock

- Close https://github.com/napi-rs/napi-rs/issues/1346

fix(napi): fallback to copy buffer if zero copy is not allowed

---

crates/napi/src/error.rs

For those who use both `feature = "noop"` and `Error` would cause a linking issue as the symbol used in `drop` may not be existed. With this PR, you can use `Error` more freely.

fix(napi): dropping Error should not call sys if feature is set to noop

---

crates/napi/src/js_values/ser.rs

https://github.com/napi-rs/napi-rs/issues/1470
serde_json::Value parses positive integers to u64 types by default. When converting serde_json::Value to a js value, those numbers are converted to BigInts, even if they are within the bounds of the number primitive. The added checks converts an u64 to an u32 if possible to prevent this behavior.

fix(napi): convert u64 to u32 in serialization

---

cli/src/build.ts
crates/macro/src/lib.rs

fix(cli): always generate typedef file even native code never changes

---

crates/sys/src/functions.rs
crates/sys/src/types.rs

I'd like to use `uv_run` in order to execute js code while waiting in some special cases, just like [deasync](https://github.com/abbr/deasync) does.
Example:
```rust
#[napi]
fn run_event_loop(env: Env) -> napi::Result<()> {
unsafe {
sys::uv_run(env.get_uv_event_loop()?, sys::uv_run_mode::UV_RUN_ONCE);
}
Ok(())
}
```

feat(napi): expose `uv_run`

---

crates/napi/src/threadsafe_function.rs
examples/napi/src/threadsafe_function.rs

If `thread_finalize_data` uses Arc::clone(), the reference count will not decrease to 0 after `ThreadsafeFunction` dropped, which will also cause node process to not exit.
```rs
pub fn function(callback: JsFunction) -> Result<()>  {
let function = callback
.create_threadsafe_function(0, ...).unwrap();
std::thread::spawn(move || {
function.call(..., ThreadsafeFunctionCallMode::Blocking);
});
Ok(())
}
```
```js
// this progress won't exit automatically
function((() => {})
```
The problem was introduced in #1515
Additional:
`impl Send + Sync` seems to be unnecessary anymore.
BTW I also remove `Pin` because I don't well know it but it seems to work well after been removed. If I have some mistake please tell me.

fix(napi): use weak arc for passing `thread_finalize_data`

---

.eslintrc.yml
crates/napi/src/bindgen_runtime/module_register.rs
crates/napi/src/tokio_runtime.rs
examples/napi/electron-renderer/index.html
examples/napi/electron-renderer/index.js
examples/napi/electron.js
examples/napi/tsconfig.json

In windows, electron renderer process will crash if:
1. Import some NAPI module that enable `tokio-rt` flag in renderer process.
2. Reload the page.
3. Call a function imported from that NAPI module.
Because the tokio runtime will be dropped when reloading the page, and won't create again, but currently we assume that the runtime must exist in tokio-based `within_runtime_if_available`.
This will cause some panic like this:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', napi-rs\crates\napi\src\tokio_runtime.rs:72:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Renderer process crashed: crashed, exitCode: -529697949
at EventEmitter.<anonymous> (napi-rs\examples\napi\electron.js:33:9)
at EventEmitter.emit …
```

Ensure tokio runtime exists when registering the module

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/module_register.rs

- Close https://github.com/napi-rs/napi-rs/issues/1504
I can confirm the double free error no longer occurred after I applied this patch to `@parcel/sourcemap` and `@parcel/hash` with `PARCEL_WORKERS=64 yarn build`.
The root cause is that `Buffer` and `TypedArray` are not zero overhead, as they bring many boundary condition processing in async context, which is a design issue. I am considering providing `&[u8/i8/...]` as a parameter to represent pure JavaScript `TypedArray`. If in synchronous usage scenarios like `@parcel/hash` and `@parcel/sourcemap`, the best option currently is to use `JsBuffer` to avoid unnecessary runtime performance degradation.
/cc @devongovett

fix(napi): free buffer in current thread if env is available

---

crates/napi/src/env.rs
crates/napi/src/js_values/object_property.rs

@victorteokw already did the bulk of the work on this but forgot to access the closure pointers properly.
This caused an access violation to come up every time external data from outside the closure was being used.
This PR aims to fixing this issue by accessing the closures from the data pointer.
See also: #1526, #1378

fix(napi): access violation in property getter/setter closure

---

crates/napi/Cargo.toml
crates/napi/src/bindgen_runtime/module_register.rs

- Fix https://github.com/napi-rs/napi-rs/issues/1356

chore(napi): add noop feature in napi crate

---

crates/backend/src/ast.rs
crates/macro/Cargo.toml
crates/macro/src/expand.rs
crates/macro/src/expand/napi.rs
crates/macro/src/expand/noop.rs
crates/macro/src/lib.rs

all non-noop code goes to `./crates/macro/src/expand/napi.rs`, no more `cfg(not(feature = "noop"))` required any more

feat: clean napi-derive noop feature code path

---

crates/backend/src/typegen.rs
crates/napi/src/bindgen_runtime/js_values.rs

Since those types can be safely cloned across the JS/Rust boundaries, we can support them by default.

chore(napi): adds support for `Rc<T>` / `Arc<T>` / `Mutex<T>`

---

cli/codegen/commands.ts
cli/docs/build.md
cli/src/api/build.ts
cli/src/def/build.ts

closes #1582
Replacing the `cargo` command with `cross` has been tested in https://github.com/web-infra-dev/rspack/actions/runs/4912599372/jobs/8771798276 by using sed to replace the command inside the script.
Example run:

feat(cli): add --use-cross command for building with `cross`

---

cli/src/api/build.ts

I actually need this feature on the v2 CLI, do you think you could backport and publish it? I used patch-package [on the Tauri PR](https://github.com/tauri-apps/tauri/pull/6861) but it's.. ugly :smile: 
I wanted to push to v2 instead but I couldn't find how you are handling it, I guess you're doing it manually?

feat(cli): detect Cargo `--profile` argument

---

crates/napi/README.md

Document riscv64 linux support status.
BTW add the missing node20 column.
The minimum working version of nodejs on riscv64 is 16. Some people tried to port node 14 to riscv64 but it is buggy.

docs(README): update platform support status

---

cli/src/build.ts
cli/src/consts.ts

Due to the implementation of v2, cli specific argument value will always be used if it has default value.
I also noticed that the `const enum` feature https://github.com/napi-rs/napi-rs/pull/1527 is not yet ported in v3.

fix(cli): ts constEnum option not working when set in package.json

---

cli/src/api/templates/js-binding.ts

Recently I merged a PR this https://github.com/lovell/detect-libc/pull/19 to improve the performance to detect `glibc` and `musl` systems.
Now, I'm porting that solution to other libraries to help them improve their performance as well.
This change improves the performance from `25ms` in most cases to `0.15ms`, so the startup of every package will be faster.
Also, after Node 20.3.0, because of https://github.com/nodejs/node/issues/48831, it could take up to `600ms` (depending on the amount of CPU), so every package that uses `napi-rs` will be slowdown by this amount of time, this especially is bad for CLIs, like swc.

perf(cli): improve musl verification

---

crates/napi/src/bindgen_runtime/js_values/map.rs

The default hasher `RandomState` for `HashMap` also implements `Default + BuildHasher`, so it's compatible with the previous version of `impl FromNapiValue`.

feat(napi): impl FromNapiValue for HashMap with custom hasher

---

crates/napi/src/bindgen_runtime/module_register.rs

I'd like to use classes created by `napi-rs` inside a Node.js instance which is created using [`rust-nodejs`](https://github.com/branchseer/rust-nodejs). For this to work, the classes need to be exported to the node runtime using `napi::bindgen_prelude::napi_register_module_v1`, which is currently not accessible from outside its module.
This PR makes this method accessible from outside its module.
<details><summary>Code I'm using to initialize <code>napi-rs</code> modules inside a node vm created by <code>rust-nodejs</code></summary>
<p>
If someone is interested in how I'm using the `napi_register_module_v1` method:
```rust
use napi::bindgen_prelude::napi_register_module_v1;
use napi::sys::{napi_env, napi_value};
use napi::Env;
use nodejs::run_raw;
use std::ffi::c_void;
use …
```

chore(napi): make napi_register_module_v1 pub

---

crates/napi/src/bindgen_runtime/module_register.rs

Hi,
I found a memory-safety/soundness issue in this crate while scanning Rust code for potential vulnerabilities. This PR contains a fix for the issue.
https://github.com/napi-rs/napi-rs/blob/30534d428803c3c8a027a6b7737c1508f68cb9bb/crates/napi/src/bindgen_runtime/module_register.rs#L64-L70
https://github.com/napi-rs/napi-rs/blob/30534d428803c3c8a027a6b7737c1508f68cb9bb/crates/napi/src/bindgen_runtime/module_register.rs#L50-L57
If a panic!() occurs between the `Vec::from_raw_parts` function, including the `Vec::from_raw_parts` function itself, and `std::mem::forget`, a double free vulnerability emerges.
In Rust, `std::mem::forget` does not actually free the memory, instead it simply allows the memory to leak. This can lead to double free when the data object goes out of scope and its …

fix(napi): potential double free issue

---

crates/napi/src/error.rs

Adds more detailed error messages when promises fail in threadsafe function by trying to coerce them to a string. This is useful in situation when an error is thrown within async function, and enables capturing of errors in such cases.
For example (in https://github.com/gorules/zen):
```ts
const { ZenEngine } = require('./index');
const engine = new ZenEngine({
loader: async (key) => {
throw Error("Custom thrown error");
}
});
(async () => {
try {
await engine.evaluate("unknown key", {});
} catch (e) {
console.log(e);
}
})();
```
Fails without "Custom thrown error" until changes above are introduced. When introduced stack is visible with e.g.:
```
[Error: Loader error: Internal error on key unknown key: GenericFailure, Error: Custom thrown error]
```

fix(napi): js promise error messages

---

crates/backend/src/codegen/enum.rs

Allows the user to not import `napi::bindgen_prelude::{FromNapiValue, ToNapiValue}` manually when using the macro.

fix(napi-derive): import `FromNapiValue` and `ToNapiValue` from `napi::bindgen_prelude` when generating an `enum`

---

cli/src/api/templates/ci-template.ts

This uses the standard way to handle npm auth in GitHub Actions.
Another improvement is to look for a tag push instead of a commit that has some line that matches a the version regex thing:
* Changing the check to `if echo "${{ github.ref_name }}" | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$";` or even `if [[ ${{ github.ref_name }} =~ ^v[0-9]\+\.[0-9]\+\.[0-9]\+$ ]];`
* Turning `tags-ignore: **` to `tags: v[0-9]*`.
* And we can then also `if` then entire publish job with `if: github.ref_type == 'tag'` to save some GitHub Actions runtime.
`then` can also be in the same line as the `if`, but that's a matter of taste.

chore(cli): simplify publish step in ci-template

---

cli/src/api/load-wasi-template.ts

1. Aligning wasi template to nodejs demo, you can refer to https://nodejs.org/api/wasi.html
2. If you are using NodeJS greater than 21, NodeJS will emit an error if you don't specify `options. version` explicitly.

fix(cli): 🤖 align wasi template to nodejs demo

---

crates/napi/src/async_work.rs

chore: fix async_work status typo

---

cli/src/api/templates/js-binding.ts

With this patch I was able to successfully use a Rust <-> NodeJS bindings built in the s390x architecture.
Might be a naive patch but I need this to get https://github.com/matrix-org/matrix-rust-sdk-crypto-nodejs to support this system without a custom build process.
Please let me know if there are other potential changes in the codebase that I should address.

feat(cli): Add support for s390x linux arch in js bindings template

---

crates/napi/src/env.rs

The resolver does not need to be `Send` or `Sync`, because it's assumed to be called from the same thread that the JavaScript thread is running on.

fix(napi): callback in execute_tokio_future does not need to be Send

---

crates/napi/src/env.rs

This is a garbage API because it simply does not work correctly, and presumably nobody uses it.

chore(napi): delete unwrap_from_ref API because it was never work

---

crates/napi/src/env.rs
crates/napi/src/js_values/value_ref.rs

This private field is never used in NAPI-RS.

chore(napi): remove napi_val on Ref because it is unused

---

crates/napi/src/env.rs
examples/napi-compat-mode/src/buffer.rs

Includes a fix for a bug introduced in #1921 where the parameters of `ptr::copy_nonoverlapping` were reversed (thus negating the intended fix for #1919).
This PR also fixes a bunch of unsoundness issues, where non-mutable pointers where expected but could actually be mutated by the JavaScript runtime in the end.

fix(napi): Fix buffer corruption and soundness issues

---

cli/src/api/universalize.ts

Using the latest alpha I had an issue using a non standard `--output-dir` with the universalize command where the JS would find the files but the XCode tool couldn't. 
I have a patch running locally with this change that resolved the issue. https://github.com/wypes-rs/wypes/blob/main/.yarn/patches/%40napi-rs-cli-npm-3.0.0-alpha.38-93961b489d.patch

Ensure cwd and outputDir are used for finding files

---

crates/napi/src/bindgen_runtime/module_register.rs

There is a piece of custom logic that has been added a while back to ensure that Buffers can be sent across threads, and be dropped properly. This involves a custom GC that runs on NodeJS's current thread (per my understanding). The logic to drop the buffer on that custom GC differed from the one in the Drop impl. This meant that everytime Node sent a buffer back to a napi-rs function, the reference wouldn't be cleaned up properly, and it would leak (96 bytes per Reference on an ARM MacOS machine).
This commit updates the logic in the custom GC so that it matches the one in the Drop impl. This worked locally, and fixed any occurence of the leak I could find.

fix(Buffer): prevent memory leak when Custom GC is used

---

crates/napi/src/js_values/object.rs

The `finalize_cb` passed to `add_finalizer` doesn't have a lifetime requirement, so it's allowed to reference things in scope. For example, this compiles fine, but it will segfault at runtime when the finalizer is called:
```rs
use napi::{JsObject, Result};
fn my_function(object: &mut JsObject) -> Result<()> {
let my_string = String::from("Hello, world!");
object.add_finalizer((), (), |_ctx| {
println!("{}", my_string);
});
drop(my_string);
}
```
This commit just requires the callback has a static lifetime which prevents the example above compiling. However the other two arguments already require static lifetimes so I'm not sure why the callback didn't.

fix(napi): JsObject.add_finalizer callback being allowed to reference non-static things

---

crates/napi/src/bindgen_runtime/js_values/promise.rs

This fix is similar to the one in https://github.com/napi-rs/napi-rs/commit/5b5f616d81ff2f0e154ff8b1e1edee1dfc087eb4.
In both the then_callback & catch_callback, expect was being called in case the send failed. This means that if we call a function that returns a promise and the received gets closed (the calling thread stopped at the wrong time), this will panic.
In such scenarios, it is fine not to panic. If the receiver doesn't care about the output, we should just let it be.

fix(napi): no panic when caller stops listening

---

crates/napi/src/env.rs

The value of `word_count` was inconsistent between the node side and rust side when calling `create_bigint_from_i128`/`create_bigint_from_u128`.

fix: `create_bigint_from_*128` returned incorrect word_count

---

crates/napi/src/threadsafe_function.rs

This was refactored in 4719caa64377f7d926c92a4c1051474ae79036c4. This codepath was swapped, as the fatal exception must be the normal codepath when the callee handled field is false. This fixes it by swapping this if statement, all the other calls have been checked and seem fine.

fix(napi): ensure CalleeHandled works as expected

---

crates/napi/src/tokio_runtime.rs
examples/napi/src/lib.rs

```rust
#[napi::module_init]
fn init() {
let rt = tokio::runtime::Builder::new_multi_thread()
.enable_all()
.on_thread_start(|| {
println!("tokio thread started");
})
.build()
.unwrap();
create_custom_tokio_runtime(rt);
}
```

feat(napi): allow user defined tokio runtime

---

cli/src/api/templates/ci-template.ts

Fix for issue https://github.com/napi-rs/napi-rs/issues/2076
Update `ci-template.ts` to fix CI error for `x86_64-apple-darwin` platform.
Although in this issue I was using the `latest` v2.18.2. Not 3.0.0-alpha.4. I believe the fix is the same for them.

Set explicit target flag for x86_64 CI template

---

cli/src/build.ts

Type definitions are generated during `cargo build`, and written to a temporary typedefs file. Usually, they are only evaluated once, but they can also be evaluated more times, when modules are loaded through [conditional compilation](https://github.com/napi-rs/napi-rs/issues/1541), by using `#[path]` attributes, or various other code patterns required to get around [existing cargo limitations](https://github.com/rust-lang/cargo/issues/8628).
This causes the temp file to have duplicate entries, which results in an invalid `index.d.ts` generated, with twice the number of types, causing `tsc` to fail with many `TS2300` errors. The issue happens with the latest released `@napi-rs/cli` version `2.18.2`.
This localized fix here deduplicates any entries found in the file, and has no effect when …

remove duplicate typedefs in `index.d.ts` from macro re-evaluation

---

crates/macro/src/compat_macro.rs
crates/napi/src/env.rs
crates/napi/src/js_values/mod.rs
examples/napi-compat-mode/src/cleanup_env.rs
examples/napi-compat-mode/src/external.rs

1. compact mode support more complex data-struct which use `ToNapiValue`.
2. Set the status of `JsExternal` as `deprecated`.
3. Update the `External` and `CleanupHook` example.

feat(napi): support External for compact mode

---

crates/napi/src/js_values/de.rs
crates/napi/src/js_values/mod.rs
crates/napi/src/js_values/object.rs
crates/napi/src/js_values/ser.rs

also adds helper functions needed to work with Ser and De
This allows more efficient serialization and deserialization of data
here is an example using both Ser and De for zerocopy messagepack encoding and decoding:
```rust
#[napi]
pub mod messagepack {
use napi::{bindgen_prelude::Buffer, Env, JsObject};
#[napi]
pub fn decode(env: Env, bytes: &[u8]) -> napi::Result<JsObject> {
let mut de = rmp_serde::Deserializer::new(bytes);
let ser = napi::Ser::new(&env);
let value = serde_transcode::transcode(&mut de, ser)?;
Ok(value.into())
}
#[napi]
pub fn encode(value: JsObject) -> napi::Result<Buffer> {
let mut de = napi::De::new(&value);
let mut ser = rmp_serde::Serializer::new(Vec::new());
serde_transcode::transcode(&mut de, &mut ser)
.map_err(|e| napi::Error::from_reason(e.to_string()))?;
let …
```

chore(napi): make Ser and De public

---

crates/napi/src/error.rs

When printed in display mode it just shows last error on the error stack but if printed in debug mode it shows the error like so:
```
failed something:
caused by failed other thing
caused by failed another thing...
```

feat(error): print anyhow error in debug mode to show trace

---

crates/napi/Cargo.toml

this additional flag tells docs.rs to use a nightly rustc to generate the documentation. Without this, all-features = true has no effect and I have tested locally that this configuration at least generates docs for all disabled features
there is a way to annotate "this function is only available with crate feature `serde`" but I'd like to first see if this change adds the documentation in general
ref for feature attrs:
- https://github.com/rust-random/rand/issues/986
- https://users.rust-lang.org/t/how-to-document-optional-features-in-api-docs/64577

let docs.rs generate all documentation

---

crates/backend/src/codegen/fn.rs
crates/napi/src/tokio_runtime.rs

Related PR:  https://github.com/napi-rs/napi-rs/pull/1583/files#diff-9da4940f977dd3497a86317635b08bdc76e6586f94bc284a9b18212649a2d543R89
Before, we weren't able to use `anyhow::Result` as the return value in asynchronous functions.
```rs
#[napi]
pub async fn test() -> napi::anyhow::Result<()> {
Ok(())
}
```
This pr will make error handling a lot easier for us.

feat(napi): asynchronous functions can return any errors

---

crates/napi/src/bindgen_runtime/js_values/string.rs

`&str` was converted to `String` with allocation.
Instead, we call `napi_create_string_utf8` directly to avoid the allocation.

perf(napi): reduce allocation for `ToNapiValue` of `&str`

---

crates/macro/src/expand/napi.rs

This is mandated by the Rust doc of the BufWriter. We've also seen bugs where the data doesn't seem to be flushed properly, and thus the CLI fails to parse JSONs emitted by napi-derive. This might be it, or not, but flushing shouldn't hurt.
@Brooooooklyn could this be added on napi2 too please? 🙏

fix(napi-derive): call flush on the BufWriter

---

crates/napi/src/bindgen_runtime/js_values/either.rs

This adds an implementation of serde::Serialize for all the Either types. Long term, we might want to use the either crate, but for now this makes this implementation usable with serde.
If this sgty @Brooooooklyn - can it be added to napi2? :)

chore: implement serde::Serialize for Either

---

crates/backend/src/codegen/struct.rs
crates/napi/src/env.rs

1、The following code will make an error, the Box::into_raw(empty struct) will return `0x1`
```
#[napi]
pub struct ZeroStruct;
#[napi]
impl ZeroStruct {
#[napi(constructor)]
pub fn new() -> Self {
ZeroStruct
}
}
#[napi(catch_unwind)]
pub fn return_zero_struct() -> ZeroStruct {
ZeroStruct
}
```
2、The ownership of the CString passed to cffi will be taken in map function.  When passed to cffi, the ctring memory has already been released

fix(napi,napi-derive): ffi lifetime and pointer sound issues

---

crates/macro/src/parser/mod.rs

Using asynchronous function for constructor will cause error.

perf(macro): constructor don't support asynchronous function

---

crates/macro/src/lib.rs

fix(derive): fix clippy warning with newer rust version

---

crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/env.rs
crates/napi/src/js_values/ser.rs

mark create_buffer as deprecated & use BufferSlice to replace JsBuffer for ser

feat(napi): mark create_buffer as deprecated & use BufferSlice to replace JsBuffer for ser

---

crates/backend/src/typegen/fn.rs

Fix  generated code for class factory: 
example: 
```rs
use napi_derive::napi;
pub struct QueryEngine {}
#[napi(js_name = "QueryEngine")]
pub struct JSQueryEngine {
engine: QueryEngine,
}
#[napi]
impl JSQueryEngine {
#[napi(factory)]
pub fn with_initial_count() -> Self {
JSQueryEngine { engine: QueryEngine {} }
}
}
```
```ts
export declare class QueryEngine {
static withInitialCount(): JsQueryEngine
}
export type JSQueryEngine = QueryEngine
```
should be:
```ts
export declare class QueryEngine {
static withInitialCount(): QueryEngine
}
export type JSQueryEngine = QueryEngine
```

fix(napi-derive-backend): should respect origin name for class factory

---

.github/workflows/test-release.yaml
crates/napi/src/bindgen_runtime/module_register.rs

Sometimes thread has not been disposed but the objects on it have been
recycled, we need to check if the data has been pointed to null before
unref it.
See https://github.com/napi-rs/napi-rs/issues/2300 for context

fix(napi): data maybe null in custom_gc

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/js_values/arraybuffer.rs

When we use `Uint8Array` in rust and pass into a `Uint16Array`, it will throw error info:
```
Error: Expected $name, got 4
at Object.<anonymous> (/Users/ranger/Desktop/project/test/napi-test/test.js:11:11)
at Module._compile (node:internal/modules/cjs/loader:1364:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
at Module.load (node:internal/modules/cjs/loader:1203:32)
at Module._load (node:internal/modules/cjs/loader:1019:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
at node:internal/main/run_main_module:28:49 {
code: 'InvalidArg'
}
```
It should be `Error: Expected Uint8Array, got Uint16Array`

chore(napi): display the real info for TypedArray

---

crates/napi/src/lib.rs

it has changed back in node.js 16.0 docs

docs: update n-api version matrix docs url

---

crates/backend/Cargo.toml

This isn't referenced in the code of the `backend` crate and is bloating the build graph unnecessarily. It seems like an oversight to me.
Tested with `cargo test` locally
```sh
grep regex -r crates/backend 
cargo test
```

chore(napi-derive): remove unused dependency `regex` from `napi-derive-backend`

---

crates/napi/src/bindgen_runtime/js_values/function.rs
examples/napi-compat-mode/__tests__/function.spec.ts
examples/napi-compat-mode/src/function.rs

We need to create nested functions to meet the ability of multi-level callback listening.
Here is an example to explain, `abilityCallback` is created by native and we need to add callback for `window.on("windowStageEvent")`
```ts
const abilityCallback = {
onAbilityForeground: ability => {
hilog.info(0x0000, "test", "onAbilityForeground")
},
onWindowStageCreate: (ability, window) => {
window.on("windowStageEvent", type => {
console.log(`${type}`)
})
}
} as AbilityLifecycleCallback;
applicationContext.on("abilityLifecycle", abilityCallback as AbilityLifecycleCallback)
```

feat(napi): allow us to create nest function from closure

---

crates/napi/src/bindgen_runtime/js_values/set.rs

I just noticed that it was missing for HashSet as well. I should have sent this together with #2374.

feat(napi): implement `ValidateNapiValue` for HashSet with any hasher

---

crates/napi/README.md

Hey there :wave:
First of all thanks for the awesome tool, it's making it easy to keep working on important stuff instead of updating glue code all the time.
The new crate versions require rust 1.80.0.
I'm not sure what the policy on this is, aren't MSRV increases supposed to be at least a minor bump?
This broke our builds since we're still on 1.78.0 for a bit and cargo picked up  the new napi-build patch version. (I'm going to go check in the Cargo.lock now)

chore: update MSRV in README.md

---

crates/napi/src/bindgen_runtime/js_values/external.rs

Hi, we recently shipped a [native bundler plugin API](https://bun.sh/docs/bundler/plugins#native-plugins) for Bun, with a Rust crate which exposes a convenient way to create native bundler plugins for Bun ([here](https://github.com/oven-sh/bun/tree/main/packages/bun-native-plugin-rs)).
Native bundler plugins in Bun are NAPI modules which expose an additional symbol to a function which implements the bundler plugin code.
To make this nicer to write in Rust, we want to allow users to integrate it with `napi-rs`.
We want to allow users to use `napi-rs` `External` type when writing native bundler plugins. Native bundler plugins can carry around the raw pointer to the napi external.
However, `napi-rs` does not mark the fields of `External` as `pub` or export anyway to go from `*mut c_void -> …

chore(napi): expose functions which turn raw pointer into External

---

crates/napi/src/bindgen_runtime/js_values/external.rs

This [commit](https://github.com/napi-rs/napi-rs/commit/4f3a4cda4690df657e472ecb7fc1d316a3e22c0e) was pushed the other day to copy my changes from #2449 into `napi2` branch
Unfortunately the copied changes introduce a subtle bug which cause it to segfault on napi major version 2.
In this version of napi, the data pointer passed to `napi_create_external()` is the `obj: *mut TaggedObject<T>` field of `External<T>` (instead of `*mut External<T>` on `main`), whereas the `External::from_raw_impl` code assumes its not a `*mut TaggedObject<T>` but a `*mut External<T>`.
Because Rust may re-order the fields of a struct, directly casting `*mut TaggedObject<T> -> *mut External<T>` is invalid

fix(napi): Update `from_raw` methods on `External<T>`

---

crates/backend/src/ast.rs
crates/backend/src/codegen/enum.rs
crates/macro/src/parser/mod.rs

fixes https://github.com/napi-rs/napi-rs/issues/2479
To reduce the nesting if branches, I put the code generation logic in separate functions.

fix(napi-derive): add `object_from_js` and `object_to_js` support for enum

---

crates/napi/src/bindgen_runtime/js_values/value_ref.rs

`Reference` should not implement the `Send` trait
Reasons:
1. Thread Safety with Node-API:
The `napi_reference_unref` function is not recommended to be called outside the JavaScript thread, as Node-API operations are generally thread-unsafe unless explicitly documented.
2. Non-Deterministic `Rc` Behavior:
The Reference type internally uses `Rc` for reference counting. When cloned and moved across threads (as shown below), the `Rc` count becomes non-deterministic, leading to potential memory safety issues or undefined behavior:
```rust
let reference1 = reference.clone(env).unwrap();
let reference2 = reference.clone(env).unwrap();
let reference3 = reference.clone(env).unwrap();
let reference4 = reference.clone(env).unwrap();
let reference5 = reference.clone(env).unwrap();
let reference6 = …
```

fix(napi): reference should not impl send trait

---

crates/build/src/wasi.rs

From my study, `--export-dynamic` isn't usually used when compiling to dynamic libraries. With this flag enable, there are many unused symbols exported from the wasm artifact. 
Rspack suffers from this with ~130,000 exported symbols, due to the 100,000 limitation of node.js, although currently there is no problem in rolldown with ~20,000 exported symbols. 
**I'm not sure whether this flag is necessary. But at least we need to find some ways to control the exports.**
I also build rolldown without this flag, and the examples in the repo can be still successfully built. Here is some data for comparison:
Data | Before | After
-- | -- | --
compilation time | 71.13s | 70.98s
export count | 20,025 | 80
wasm size(debug) | 169.93MB | 167.15MB
wasm size | 14.99MB |  11.91MB
Example | Before (ms) | …

perf(build): remove `--export-dynamic` flag in wasi compilation

---

crates/napi/src/bindgen_runtime/js_values/bigint.rs

This fixes issues with marshalling of a `BigInt` to Rust native types.

fix: backport BigInt changes from #2028 & #2356

---

wasm-runtime/fs-proxy.cjs

fix(wasm-runtime): remove `_isBuffer` patch

---

crates/backend/src/codegen/fn.rs
examples/napi-compat-mode/src/napi4/tsfn.rs

- Close https://github.com/napi-rs/napi-rs/issues/2571

fix(napi-derive): make_ref with Vec<&S> cases

---

cli/src/utils/metadata.ts

The way the `cargo metadata` command is currently run is prone to failure because the path is not escaped. The best way to handle this is to pass the arguments directly as separate to the `cargo` process through `spawnSync` so there is no need to rely on manual escaping.
Please let me know if there is anything else I should edit before this can be merged!
I am currently using NAPI v3 so I can also put in the work to get it merged to that version following your guidance.
Here is an example of what happens when the project is run in a path that has a space in the name of a folder.

fix: Fix path escaping issue in metadata parser

---

crates/napi/src/bindgen_runtime/js_values/class.rs

Fix lifetime specification for ClassInstance::as_object method
The returned Object's lifetime should be tied to the input Env's lifetime, not the ClassInstance itself.

fix: ClassInstance as_object lifecycle

---

bench/src/get_set_property.rs
crates/backend/src/codegen/struct.rs
crates/napi/src/bindgen_runtime/js_values/class.rs
crates/napi/src/js_values/object_property.rs
examples/napi-compat-mode/src/class.rs
examples/napi-compat-mode/src/napi4/mod.rs
examples/napi-compat-mode/src/object.rs
examples/napi/__tests__/values.spec.ts
examples/napi/src/class.rs
examples/napi/src/object.rs

Refactor the `Property` struct and can pass symbol as name.
when pass symbol as name
```rust
let line_join_symbol = env.create_symbol(Some("lineJoins"))?;
Property::new()
.with_name(env, line_join_symbol)?;
```
when pass str as name
```rust
Property::new()
.with_utf8_name("miterNative")?;
```

feat!(napi): define propertes support symbol as name

---

crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs
crates/napi/src/bindgen_runtime/js_values/buffer.rs
crates/napi/src/bindgen_runtime/js_values/value_ref.rs
crates/napi/src/bindgen_runtime/mod.rs
crates/napi/src/bindgen_runtime/module_register.rs

Performance analysis revealed unexpected overhead in `napi::bindgen_runtime::module_register::PersistedPerInstanceHashMap<K,V>::borrow_mut`.
Optimizations
1. Lock mechanism refinement for PersistedPerInstanceHashMap
Replaced internal `RwLock` with `RefCell` since this struct doesn't require Send + Sync implementation, eliminating thread synchronization overhead.
2. Thread-local initialization
Initialized the following global variables via `thread_local!` macro for thread safety:
- REGISTERED_CLASSES
- FN_REGISTER_MAP
- THREADS_CAN_ACCESS_ENV
3. Cross-thread sharing enhancement
Refactored `ModuleClassProperty` into a struct guarded by `RwLock` to enable safe sharing between JS main thread and worker threads via `MODULE_CLASS_PROPERTIES`.

perf(napi): PersistedPerInstanceHashMap can be thread local

---

crates/napi/src/bindgen_runtime/js_values/function.rs
crates/napi/src/threadsafe_function.rs
examples/napi/src/threadsafe_function.rs

Continue on the comment of https://github.com/napi-rs/napi-rs/pull/2694
Related comment: https://github.com/napi-rs/napi-rs/pull/2694#issuecomment-2944864476
Reverted https://github.com/napi-rs/napi-rs/pull/2694. Won't consider this as a breaking change either, since we've removed the old implementation and the old one haven't been released yet.

feat(napi): support setting `error_status` of `ThreadsafeFunctionBuilder`

---

crates/napi/src/bindgen_runtime/js_values/object.rs

Maybe can resolve https://github.com/napi-rs/napi-rs/issues/2708, also boost some perf

fix(napi): avoid add finalizer if properties is empty

---

crates/napi/src/bindgen_runtime/js_values/stream/read.rs
crates/napi/src/threadsafe_function.rs

In ThreadsafeFunction::call_with_return_value

fix(napi): callback should be Fn rather than FnOnce

---

cli/src/api/build.ts
cli/src/api/templates/load-wasi-template.ts
cli/src/utils/config.ts

From https://emnapi-docs.vercel.app/reference/list.html#buffer-related we should the Buffer polyfill is needed in browser for Buffer related api.
I'm not sure whether bundle `buffer` to `@napi-rs/wasm-runtime` is a better choice.

feat(cli): add `buffer` to wasi browser template

---

cli/codegen/index.ts
cli/package.json
cli/src/api/rename.ts
cli/src/utils/config.ts
cli/src/utils/typegen.ts
cli/tsdown.config.ts
package.json
triples/generate-triple-list.ts
triples/package.json
yarn.lock

Merge #2860 first
[`es-toolkit`](https://es-toolkit.dev/) is a modern alternative to `lodash`, offering dual module format support and a significantly smaller bundle size.

refactor: replace `lodash-es` with `es-toolkit`

---

cli/src/api/pre-publish.ts

Allow to retry failed publish CI jobs

chore(cli): skip already published native packages

---

cli/src/utils/misc.ts

Replaces promisified node:fs methods with direct usage of node:fs/promises for async file operations. Updates fileExists to use access instead of stat for existence checks.

refactor(cli): fs utils to use fs/promises API

---

wasm-runtime/package.json
yarn.lock

This PR updates `@tybys/wasm-util` package to the latest version 0.10.1
In this version `process.env` access were handled gracefully in order to not fail at runtime for some bundlers
See https://github.com/toyobayashi/wasm-util/issues/4 for more details
Closes https://github.com/napi-rs/napi-rs/issues/2867

chore(wasm-runtime): update @tybys/wasm-util in order to avoid runtime error with access to process.env.NODE_DEBUG_NATIVE

---

crates/build/src/wasi.rs

emnapi 1.5.0 allows calling wasi-libc's blocking calls in browser main thread (will work in rust 1.90.0 according to https://github.com/toyobayashi/emnapi/issues/159#issuecomment-3175658724).
More context:
- https://github.com/toyobayashi/emnapi/issues/159
- https://github.com/toyobayashi/emnapi/pull/160
- https://github.com/napi-rs/napi-rs/issues/2809#issuecomment-3163916783

fix(build): export `emnapi_thread_crashed`

---

cli/package.json
cli/src/api/rename.ts
yarn.lock

Replace `find-up` (5 deps) with `empathic` (0 deps) for searching directories upwards. This reduces the dependencies installed for `@napi-rs/cli`
The source code for empathic's find function can be found [here](https://github.com/lukeed/empathic/blob/f5f944a06f9a411168a0073c3fe14e517031d098/src/find.ts#L77-L88).

chore(cli): replace find-up with empathic

---

cli/src/api/artifacts.ts
cli/src/api/build.ts
cli/src/api/create-npm-dirs.ts
cli/src/api/new.ts
cli/src/api/pre-publish.ts
cli/src/api/rename.ts
cli/src/api/universalize.ts
cli/src/api/version.ts
cli/src/commands/new.ts
cli/src/utils/config.ts
cli/tsconfig.json

When running `yarn build` in `cli/`, I notice there were many warnings such as:
```
[MISSING_EXPORT] Warning: "UniversalizeOptions" is not exported by "src/def/universalize.ts".
╭─[ src/api/universalize.ts:6:3 ]
│
6 │   UniversalizeOptions,
│   ─────────┬─────────  
│            ╰─────────── Missing export
│ 
│ Note: If you meant to import a type rather than a value, make sure to add the `type` modifier (e.g. `import { type Foo } from '../def/universalize.js'`).
───╯
```
So I added the type imports to fix the warnings. I also add `"verbatimModuleSyntax": true` to `cli/tsconfig.json` so the errors are shown in the IDE / before-build directly.

chore(cli): add type imports
